version: "3.3"

services:
  db:
    build: ./db/.
    ports:
      - "3306:3306"
  was:
    build: .
    ports:
      - "8080:8080"
    links:
      - "db:database"
    depends_on:
      - db

# run "gradle java-was" for artifect
