SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS USERS CASCADE;
CREATE TABLE IF NOT EXISTS USERS
(
    ID       BIGINT AUTO_INCREMENT,
    USER_ID  VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR(20)        NOT NULL,
    NAME     VARCHAR(20)        NOT NULL,
    EMAIL    VARCHAR(50)        NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS MEMOS CASCADE;
CREATE TABLE IF NOT EXISTS MEMOS
(
    MEMO_ID      BIGINT AUTO_INCREMENT,
    WRITER_ID    VARCHAR(20) NOT NULL,
    CONTENT      VARCHAR(500),
    CREATED_DATE TIMESTAMP   NOT NULL,
    FOREIGN KEY (WRITER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (MEMO_ID)
);

SET FOREIGN_KEY_CHECKS = 1;
