DROP TABLE IF EXISTS POSTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID      VARCHAR(255) PRIMARY KEY,
    PASSWORD     VARCHAR(255),
    NAME         VARCHAR(255),
    EMAIL        VARCHAR(255),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POSTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER       VARCHAR(255),
    CONTENT      VARCHAR(255),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);
