DROP TABLE IF EXISTS POSTS;

CREATE TABLE IF NOT EXISTS POSTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    CREATED_DATE DATETIME,
    WRITER       VARCHAR(255),
    CONTENT      VARCHAR(255)
);
